spring:
  application:
    name: cloud-movie-front

server:
  port: 8080

management:
  security:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds:  60000
